services:
  front:
    build: ./front
    depends_on:
      - database
      - back
    network_mode: host
    ports:
      - 5173:5173

  back:
    build: ./back
    depends_on:
      - database
    network_mode: host
    ports:
      - 8888:8888

  database:
    image: 'postgres:latest'
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=superpass
    network_mode: host
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
