version: '3'

services:
  front:
    build: ./front
    depends_on:
      - database
      - back
    ports:
      - 5173:5173

  back:
    build: ./back
    depends_on:
      - database
    ports:
      - 8888:8888

  database:
    image: 'postgres:latest'
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=superuser
      - POSTGRES_PASSWORD=superpass
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: nait@nait.com
      PGADMIN_DEFAULT_PASSWORD: sunny
    depends_on:
      - database


networks: 
  postgres-network:
    driver: bridge
